### ISSUE TITLE
Cyclomatic Complexity build result success case should look like failure case

### ISSUE THREAD

**Issue by gt-dbechtold** [GrammaTech/jenkins-codesonar-plugin#14]
Currently, if the user specifies the "Cyclomatic Complexity" condition, and if the condition evaluation succeeds, the build page will show a message like:

* Cyclomatic complexity [All cyclomatic complexity values within threshold 9]: SUCCESS

However, if it fails it will look like:

* Cyclomatic complexity [threshold=8, complexity=9 (procedure: 'main')]: UNSTABLE

I think the success case should look like the failure case and we should still print the maximum complexity, for example:

* Cyclomatic complexity [threshold=9, complexity=9 (procedure: 'main')]: SUCCESS

I suppose we can debate whether "complexity=9" is preferable to "maximum-complexity=9", but my opinion is that it should just say "complexity" - in the interest of being concise and at the risk of being confusing to users.

**Comment by aseno-grammatech** [comment]
Addressed in PR #16
