### ISSUE TITLE
warningCountIncreaseOverall build result text shows incorrect numbers.

### ISSUE THREAD

**Issue by gt-dbechtold** [GrammaTech/jenkins-codesonar-plugin#15]
Currently, the `warningCountIncreaseOverall` condition can produce build result text like the following:

> Warning count increase: overall [threshold=1.00%, increase=1.96% (count: current=1, previous=51)]: FAILURE

Notice the part that says `current=1, previous=51`.  

I think we should print the total number of warnings found in both cases.  The "current" count, should not show the "diff", instead it should show the total count of warnings for the current analysis (e.g. 52, not 1):

> count: current=52, previous=51

**Comment by aseno-grammatech** [comment]
Addressed in PR #16
