### ISSUE TITLE
warningCountIncreaseSpecifiedScoreAndHigher incorrect evaluation

### ISSUE THREAD

**Issue by gt-dbechtold** [GrammaTech/jenkins-codesonar-plugin#17]
It appears that the `warningCountIncreaseSpecifiedScoreAndHigher` is intended to compare the warnings from the current build to the warnings in the previous build, but the code doesn't actually look at the previous build.  Instead it appears to calculate the percentage of the warnings in the current analysis that have a *score* exceeding the threshold.

Current help documentation says:

> Set the build result to result if the number of warnings with rank minrank or higher issued by the CodeSonar analysis exceeds the number issued for the previous analysis by more than limit%. 

The code computes the warning "increase" percentage as follows:

    calculatedWarningPercentage = ((float) severeWarnings / totalNumberOfWarnings) * 100;

Where `severeWarnings` is the number of warnings from the current analysis that exceed the input `rankOfWarnings` threshold (which is actually a *score*).

The fact that the code compares warning *scores* and not *ranks* deserves a different issue report.

**Comment by gt-dbechtold** [comment]
> The fact that the code compares warning _scores_ and not _ranks_ deserves a different issue report.

See Issue #18

**Comment by aseno-grammatech** [comment]
Addressed in PR #16
