### ISSUE TITLE
Plugin memory usage concerns

### ISSUE THREAD

**Issue by gt-dbechtold** [GrammaTech/jenkins-codesonar-plugin#9]
While working on some unrelated bug fixes, we discovered that the plugin appears to download all warnings and procedures found in an analysis.  The data is loaded into memory and appears to get persisted in each build.  If the number of warnings or procedures becomes quite large, this could lead to memory failures in the Jenkins controller.  The plugin should try to use the CodeSonar hub API to search for the data that it needs rather than reading it entirely into memory.  If the hub API is not sufficient to narrow down the results, then the plugin should stream the data from the server rather than loading it all into memory.  The plugin should probably not store unbounded lists of anything in the Jenkins builds, but should rather store fixed-sized units, such as the analysis ID, warning count, etc.

**Comment by gt-dbechtold** [comment]
See PR #16

**Comment by aseno-grammatech** [comment]
Addressed in PR #16
